name: Node.js build react-app

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-react-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci && npm ci --prefix react-app
      - name: Build
        run: npm run build --prefix react-app
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-app-build
          path: react-app/build
