name: Node.js build react-app

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-react-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            react-app/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        working-directory: react-app
        run: npm ci --no-audit --no-fund
      - name: Build
        working-directory: react-app
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: react-app-build
          path: react-app/build
